version: '3.8'

services:
  app:
    build: .
    container_name: ordermanager
    environment:
      GORM_DNS: ${GORM_DNS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_SENDER: ${SENDER}
      EMAIL_SENDER_PASSWORD: ${PASSWORD}
      SEND_MAIL_TIME_POINT1: ${SEND_MAIL_TIME_POINT1}  #9:00 AM
      SEND_MAIL_TIME_POINT2: ${SEND_MAIL_TIME_POINT2}  #13:00 PM
      LOG_PATH: ${LOG_PATH}
      ADMIN: ${ADMIN}
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "13306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"

volumes:
  db_data:
