version: '3.8'

services:
  app:
    build: .
    container_name: ordermanager
    environment:
      GORM_DNS: "root:123123@tcp(db:3306)/ordermanager?charset=utf8mb4&parseTime=True&loc=Local"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: ordermanager
      MYSQL_USER: dusong
      MYSQL_PASSWORD: 123123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  db_data:
